Ww11 gtest
projectceladon/camera-vhal pull request #14
Opened 2023-03-13 17:09 UTC by Sapna1-singh

2023-03-14 12:36 UTC, JeevakaPrabu requested changes

2023-03-14 12:36 UTC, JeevakaPrabu commented on src/ClientCommunicator.cpp
>          ALOGI("%s(%d): Received fd %d", __FUNCTION__, mClientId, mClientFd);
getClientFd should be in a while loop until fd is valid.

2023-03-14 12:36 UTC, JeevakaPrabu commented on src/ConnectionsListener.cpp
> +    strncpy(&addr_un.sun_path[0], mSocketPath.c_str(), fmin(strlen(mSocketPath.c_str()),strlen(addr_un.sun_path)));
use std::min as fmin returns float

2023-03-14 12:36 UTC, JeevakaPrabu commented on src/ConnectionsListener.cpp
> +    ALOGI(" %s camera socket server file %s will created. ", __FUNCTION__, mSocketPath.c_str());
will => is

2023-03-14 12:36 UTC, JeevakaPrabu commented on src/ClientCommunicator.cpp
> +                break;
break is not intended. please use [[fallthrough]];

2023-03-15 08:14 UTC, akodanka commented on src/fake-pipeline2/JpegCompressor.cpp
> +        mBuffers = nullptr;
Why is this changed ?

2023-03-15 08:14 UTC, akodanka commented on src/ConnectionsListener.cpp
> +                    close(new_client_fd);
Since we are getting an incorrect packet from the Streamer, the only way to restore the connection would be to re-establish a new connection.
In that case, if we close the fd here, it might trigger a reconnect sequence at libvhal-client too : 
https://github.com/projectceladon/libvhal-client/blob/main/source/video_sink_impl.h#L103

2023-03-15 08:14 UTC, akodanka commented on src/ConnectionsListener.cpp
> +                if (client_id >= mNumConcurrentUsers) {
Why did we remove the check for < 0 ?

2023-03-15 08:14 UTC, akodanka commented on src/ConnectionsListener.cpp
> +	    close(new_client_fd);
Why is this close needed ? Wouldn't it close the connection soon after  establishing a connection ?

2023-03-15 12:54 UTC, Sapna1-singh commented on src/ConnectionsListener.cpp
> +        if (!mClientsConnected[client_id])
so that we can avoid printing this log again and again for same client.
Without this check this log will come once every 3 sec

2023-03-16 03:14 UTC, akodanka commented on src/ConnectionsListener.cpp
> +            new_client_fd = ::accept(mSocketServerFd, (struct sockaddr *)&addr_un, &alen);
I think you might still want to close this socket at certain places where you are losing this variable :
Line#166 : Not required because the new_client_fd itself is invalid.
Line#176 : Required because the new_client_fd is not stored anywhere, and is going to get a new value at the next iteration.
Line#192, #198, #202 : Same as Line#176.

2023-03-16 05:55 UTC, akodanka commented on src/ClientCommunicator.cpp
> +                ALOGVV("%s(%d): Decoding started now.", __func__, mClientId);
Was the `[[fallthrough]];` introduced to fix a coverity error ? If so, you might have missed that here again.

2023-03-16 05:55 UTC, akodanka commented on src/ConnectionsListener.cpp
> +                close(new_client_fd);
> Line#166 : Not required because the new_client_fd itself is invalid.

This is invalid right ? new_client_fd < 0 , and attempting to close it ?

2023-03-16 06:39 UTC, akodanka approved these changes
LGTM

2023-03-16 14:19 UTC, JeevakaPrabu approved these changes

2023-03-16 15:11 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/940

2023-03-16 17:39 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/941

Done by "Singh, Sapna1" <sapna1.singh@intel.com>

2023-03-17 09:07 UTC, JeevakaPrabu approved these changes

2023-03-17 13:35 UTC, akodanka approved these changes

2023-03-18 12:27 UTC, akodanka commented on src/ConnectionsListener.cpp
> +void ConnectionsListener::requestExit(int clientId) {
Not sure if this is the right functionality that we are targeting.
If we are looking for a clean exit of the ConnectionsListener as well as all ClientCommunicator Threads, we shouldn't be accepting any parameters here.
Instead we should go ahead and set_value for all the Client promises.

Issue with the current code :
It is setting mRunning to false for the Listener, and only unblocking one of the ClientIds.

2023-03-18 12:32 UTC, JeevakaPrabu requested changes

2023-03-18 12:32 UTC, JeevakaPrabu commented on src/ConnectionsListener.cpp
> +void ConnectionsListener::requestExit(int clientId) {
agree. We should unblock all clients and not only 1 specific client

2023-03-19 04:31 UTC, JeevakaPrabu requested changes

2023-03-19 04:31 UTC, JeevakaPrabu commented on src/ConnectionsListener.cpp
> +    for (int clientId = 0; clientId < mNumConcurrentUsers; clientId++)
As mClientFdPromises is a vector, is it better to use mClientFdPromises.size instead of mNumConcurrentUsers?

2023-03-19 06:55 UTC, JeevakaPrabu approved these changes

2023-03-20 05:26 UTC, akodanka commented on src/ConnectionsListener.cpp
> +        mClientFdPromises[clientId].set_value(-1);
You might have to check for mClientsConnected[clientId] before setting this value.
Because, if you try to set the value for a promise which has already been set earlier, it might cause an exception.

Does this scenario work fine in gtest : 
Start vhal > Connect Streamer > Attempt cleanup(requestExit).
By the time you call requestExit, mClientFdPromises[0] already has a value set from the streamer connection. So, it should throw an exception.

2023-03-20 07:42 UTC, akodanka approved these changes
LGTM

2023-03-20 07:53 UTC, JeevakaPrabu approved these changes

2023-03-20 09:58 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/942

Done by "Singh, Sapna1" <sapna1.singh@intel.com>

2023-03-23 08:49 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/948

Done by "Singh, Sapna1" <sapna1.singh@intel.com>

2023-03-23 08:55 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/android_cloud-premerge/builds/488

Done by "Singh, Sapna1" <sapna1.singh@intel.com>

2023-03-23 10:21 UTC, merged

2023-03-23 10:21 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Singh, Sapna1" <sapna1.singh@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/android_cloud-mergerequest/builds/500