Fix for black camera preview observed in AIC app for H265 config
projectceladon/camera-vhal pull request #9
Opened 2023-01-19 09:37 UTC by Sapna1-singh

When camera is launched using the AIC-Client application, there is no preview and a black screen is seen.

once the camera-vhal receives the encoded frame from client, it will decode the frame but In this case, after receiving the frame from client, decoding the frame is failing with error code -14 that is MFX_ERR_INCOMPATIBLE_VIDEO_PARAM error.

Decoder param codeclevel was not set correctly.

Whenever it fails with this error, re-intialize the decoder with default value instead of using static value.

Tracked-on: OAM-105522
Signed-off-by: Singh, Sapna1 <sapna1.singh@intel.com>

2023-01-23 08:29 UTC, JeevakaPrabu approved these changes

2023-01-23 08:44 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/890

2023-01-23 08:55 UTC, JeevakaPrabu approved these changes

2023-01-23 08:56 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/891

2023-01-23 09:11 UTC, JeevakaPrabu approved these changes

2023-01-23 10:09 UTC, akodanka requested changes

2023-01-23 10:09 UTC, akodanka commented on src/onevpl-video-decode/MfxDecoder.cpp
> +    if (!mIsDecoderInitialized) {
I have a concern with the Release sequence.

In VirtualFakeCamera3::closeCamera(), we have this sequence : 
```
        mClientThread->mCameraSessionState = socket::CameraSessionState::kCameraClosed;
        mDecoder->Release();```
Between the above 2 lines, there could be a DecodeFrame call from the ClientCommunicator(Very rare scenario during the transition of mCameraSessionState).
If that happens, there is a possibility that : 
1) Release locks mDecMutex and sets mIsDecoderInitialized to false.
2) DecodeFrame gets locked at mDecMutex, and when acquires it, the mIsDecoderInitialized is false, and might attempt InitDecoder()

2023-01-23 11:05 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/892

Done by "Singh, Sapna1" <sapna1.singh@intel.com>

2023-01-23 16:01 UTC, Sapna1-singh commented on src/onevpl-video-decode/MfxDecoder.cpp
> +    mfxBitstream *bs = mMfxFrameConstructor->GetMfxBitstream().get();
Yes  we need this line as this bs(bitstream is passed to decodeAsync API).
MFXVideoDECODE_DecodeFrameAsync(mMfxDecSession, bs, pWorkSurface,&pOutSurface, &sync_point); - line no - 492

2023-01-23 16:32 UTC, Sapna1-singh commented on src/onevpl-video-decode/MfxDecoder.cpp
> +        ALOGE("%s: Current decoding couldn't be terminated. Failed.", __func__);
This API gets called only when  MFXVideoDECODE_Init API fails and error code of this API will be sent to the caller along with a success or failure log of  MFXVideoDECODE_Close API.
In case FreeDecoder passes, we are setting the flag to false which will be checked in DecodeFrame API and since it is false, it means deinit of decoder is success and we can reinit the video decoder whereas when it fails, we can't reinitialize the decoder and decoding will fail with MFX_ERR_INCOMPATIBLE_VIDEO_PARAM error.

2023-01-24 06:50 UTC, akodanka approved these changes
LGTM

2023-01-24 06:57 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/893

2023-01-24 07:00 UTC, JeevakaPrabu approved these changes

2023-01-24 07:03 UTC, JeevakaPrabu approved these changes

2023-01-24 08:28 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/894

Done by "Singh, Sapna1" <sapna1.singh@intel.com>

2023-01-24 17:17 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/895

Done by "Singh, Sapna1" <sapna1.singh@intel.com>

2023-01-24 17:18 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/android_cloud-premerge/builds/459

Done by "Singh, Sapna1" <sapna1.singh@intel.com>

2023-01-24 18:22 UTC, merged

2023-01-24 18:23 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Singh, Sapna1" <sapna1.singh@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/android_cloud-mergerequest/builds/474